### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by peterthorpe5** [samebdon/heRho#3]
Dear heRho, 

I am trying to run your tools on a multi sample VCF (called using GATK, merged using GLNexus). However, it consistently fails. Would you please help to find the issues?
regards, Pete

Command: (software is a conda env as instructed in your readme)
 python ./heRho/heRho/heRho_tally_pairwise_counts_vcf.py --vcf Dpse_MV25_final.vcf   -f herho_test 

    for chrom_df in results:
  File "/shelf/apps/pjt6/conda/envs/herho/lib/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/shelf/apps/pjt6/conda/envs/herho/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/shelf/apps/pjt6/conda/envs/herho/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/shelf/apps/pjt6/conda/envs/herho/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/shelf/apps/pjt6/conda/envs/herho/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/shelf/apps/pjt6/conda/envs/herho/lib/python3.9/concurrent/futures/process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/shelf/apps/pjt6/conda/envs/herho/lib/python3.9/concurrent/futures/process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "./heRho/heRho/heRho_tally_pairwise_counts_vcf.py", line 110, in tally_chroms_worker
    self.chrom_obj_dict[chromosome].parse_vcf()
  File "./heRho/heRho/heRho_tally_pairwise_counts_vcf.py", line 263, in parse_vcf
    last_snp = snp_pos[-1]
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by samebdon** [comment]
Hello! What do the column headers for your VCF file look like?

**Comment by peterthorpe5** [comment]
thank you for your reply, yes, so:

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	s1	s100	s101	s102	s104	s105	s106	s107	s108	s109	s11	s110	s111	s112	s113	s114	s115	s116	s117	s119	s12	s121	s122	s123	s124	s125	s126	s127	s128	s129	s13	s130	s131	s132	s133	s134	s135	s136	s139	s140	s141	s142	s143	s144	s145	s146	s147	s148	s149	s151	s154	s155	s156	s157	s158	s159	s160	s161	s162	s163	s164	s165	s17	s18	s21	s24	s25	s27	s29	s3	s30	s31	s32	s33	s34	s35	s37	s39	s40	s42	s43	s46	s47	s48	s49	s5	s50	s51	s53	s54	s55	s56	s57	s58	s59	s6	s60	s61	s62	s63	s64	s67	s68	s69	s7	s70	s72	s73	s74	s76	s77	s78	s8	s80	s81	s82	s83	s9	s90	s92	s95	s96	s98

**Comment by peterthorpe5** [comment]
The full headers are as as so:


##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency estimate for each alternate allele">
##INFO=<ID=AQ,Number=A,Type=Integer,Description="Allele Quality score reflecting evidence for each alternate allele (Phred scale)">
##FILTER=<ID=MONOALLELIC,Description="Site represents one ALT allele in a region with multiple variants that could not be unified into non-overlapping multi-allelic sites">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=RNC,Number=2,Type=Character,Description="Reason for No Call in GT: . = n/a, M = Missing data, P = Partial data, D = insufficient Depth of coverage, - = unrepresentable overlapping deletion, L = Lost/unrepresentable allele (other than deletion), U = multiple Unphased variants present, O = multiple Overlapping variants present, 1 = site is Monoallelic, no assertion about presence of REF or ALT allele">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=SB,Number=4,Type=Integer,Description="Per-sample component statistics which comprise the Fishers Exact Test to detect strand bias.">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Phred-scaled genotype Likelihoods">
##contig=<ID=NC_046679.1,length=32422566>
##contig=<ID=NC_046680.1,length=23510042>
##contig=<ID=NC_046681.1,length=30706867>
##contig=<ID=NC_046682.1,length=1881070>
##contig=<ID=NC_046683.1,length=68158638>
##contig=<ID=NW_022881696.1,length=82927>
##contig=<ID=NW_022881697.1,length=460729>
##contig=<ID=NW_022881698.1,length=114244>
##contig=<ID=NW_022881699.1,length=40347>
##contig=<ID=NW_022881700.1,length=46457>
##contig=<ID=NW_022881701.1,length=87335>
##contig=<ID=NW_022881702.1,length=81596>
##contig=<ID=NW_022881703.1,length=112890>
##contig=<ID=NW_022881704.1,length=79628>
##contig=<ID=NW_022881705.1,length=130757>
##contig=<ID=NW_022881706.1,length=16863>
##contig=<ID=NW_022881707.1,length=319238>
##contig=<ID=NW_022881708.1,length=806708>
##contig=<ID=NW_022881709.1,length=118085>
##contig=<ID=NW_022881710.1,length=401457>
##contig=<ID=NW_022881711.1,length=61596>
##contig=<ID=NW_022881712.1,length=264556>
##contig=<ID=NW_022881713.1,length=101004>
##contig=<ID=NW_022881714.1,length=85906>
##contig=<ID=NW_022881715.1,length=241509>
##contig=<ID=NW_022881716.1,length=55907>
##contig=<ID=NW_022881717.1,length=57275>
##contig=<ID=NW_022881718.1,length=94035>
##contig=<ID=NW_022881719.1,length=3964>
##contig=<ID=NW_022881720.1,length=6095>
##contig=<ID=NW_022881721.1,length=4649>
##contig=<ID=NW_022881722.1,length=2864>
##contig=<ID=NW_022881723.1,length=7162>
##contig=<ID=NW_022881724.1,length=3211>
##contig=<ID=NW_022881725.1,length=3891>
##contig=<ID=NW_022881726.1,length=3404>
##contig=<ID=NW_022881727.1,length=1979>
##contig=<ID=NW_022881728.1,length=3958>
##contig=<ID=NW_022881729.1,length=204008>
##contig=<ID=NW_022881730.1,length=139783>
##contig=<ID=NW_022881731.1,length=122710>
##contig=<ID=NW_022881732.1,length=103992>
##contig=<ID=NW_022881733.1,length=354467>
##contig=<ID=NW_022881734.1,length=428893>
##contig=<ID=NW_022881735.1,length=104203>
##contig=<ID=NW_022881736.1,length=134729>
##contig=<ID=NW_022881737.1,length=93842>
##contig=<ID=NW_022881738.1,length=279765>
##contig=<ID=NW_022881739.1,length=38819>
##contig=<ID=NW_022881740.1,length=47904>
##contig=<ID=NW_022881741.1,length=25075>
##contig=<ID=NW_022881742.1,length=1533>
##contig=<ID=NW_022881743.1,length=39719>
##contig=<ID=NW_022881744.1,length=2908>
##contig=<ID=NW_022881745.1,length=90301>
##contig=<ID=NW_022881746.1,length=58799>
##contig=<ID=NW_022881747.1,length=48128>
##contig=<ID=NW_022881748.1,length=40881>
##contig=<ID=NW_022881749.1,length=30447>
##contig=<ID=NW_022881750.1,length=172412>
##contig=<ID=NW_022881751.1,length=3778>
##contig=<ID=NW_022881752.1,length=3752>
##contig=<ID=NW_022881753.1,length=6054>
##contig=<ID=NW_022881754.1,length=45809>
##contig=<ID=NW_022881755.1,length=50475>
##contig=<ID=NW_022881756.1,length=6037>
##contig=<ID=NW_022881757.1,length=1117>
##contig=<ID=NW_022881758.1,length=1987>
##contig=<ID=NW_022881759.1,length=3115>
##contig=<ID=NC_046603.1,length=16118>
##GLnexusVersion=v1.1.5-1-gd7b4307
##GLnexusConfig=gatk
##GLnexusConfigCRC32C=4268227464
##bcftools_viewVersion=1.9+htslib-1.9
##bcftools_viewCommand=view all_samples.bcf; Date=Mon Jan 24 10:56:24 2022
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	s1	s100	s101	s102	s104	s105	s106	s107	s108	s109	s11	s110	s111	s112	s113	s114	s115	s116	s117	s119	s12	s121	s122	s123	s124	s125	s126	s127	s128	s129	s13	s130	s131	s132	s133	s134	s135	s136	s139	s140	s141	s142	s143	s144	s145	s146	s147	s148	s149	s151	s154	s155	s156	s157	s158	s159	s160	s161	s162	s163	s164	s165	s17	s18	s21	s24	s25	s27	s29	s3	s30	s31	s32	s33	s34	s35	s37	s39	s40	s42	s43	s46	s47	s48	s49	s5	s50	s51	s53	s54	s55	s56	s57	s58	s59	s6	s60	s61	s62	s63	s64	s67	s68	s69	s7	s70	s72	s73	s74	s76	s77	s78	s8	s80	s81	s82	s83	s9	s90	s92	s95	s96	s98

**Comment by samebdon** [comment]
Great thank you. Apologies but would you be able to send me a couple lines of data? I am unsure at a glance but I would be glad to look at figuring this out using an example.

**Comment by peterthorpe5** [comment]
[example.zip](https://github.com/samebdon/heRho/files/8658743/example.zip)
I have done zipped head -n 3000 > example.vcf ...

If you require more, I will have to share to an email address?

cheers,

Pete

**Comment by samebdon** [comment]
Hi Pete, that is great thanks a bunch. So I had assumed the VCF file contains a NUMALT field as part of filtering (for NUMALT==1). I have now pushed a change so if your VCF file doesn't have a NUMALT field it will assume NUMALT==1. With this change I managed to run the script on your example file. You will still get a warning from scikit-allel, but hope this helps for now.

**Comment by peterthorpe5** [comment]
superb - thank you for your fast response and help!!
