### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by ThomasBrazier** [samebdon/heRho#4]
Hi,

Thanks for the package. I have a potential fix for a bug and a theoretical question:

(1) Bug fix.

A ValueError is raised if some columns of the tsv dataframe are automatically encoded as numeric (i.e. sample_name and chromosome). For example, if chromosome names are 1, 2, 3... they are considered as numeric and considered in 'test = test.groupby(["distance"], as_index=False).sum()' line 31. Hence they are unpacked and lead to the following error:

Line 45, in calc_single_dist
    d, h0, h1, h2, th = x
ValueError: too many values to unpack (expected 5)

I found that a solution to prevetn this is to force these columns to be of type string just after reading the file by adding the lines
df["sample_name"] = df["sample_name"].astype(str)
df["chromosome"] = df["chromosome"].astype(str)

just after 'df = pd.read_csv(fileIn, delimiter="\t")' at line 160.

I will ask the theoretical question in a second thread.

Thank you,

Thomas Brazier

**Comment by samebdon** [comment]
Super, thanks for spotting this and finding a fix. I will make the relevant changes and post here once I have uploaded them.

**Comment by ThomasBrazier** [comment]
You're welcome. A more elegant fix would be to specify the expected type of each column directly in pd.read_csv() using the 'dtype' option.
