### ISSUE TITLE
Invariant sites

### ISSUE THREAD

**Issue by ThomasBrazier** [samebdon/heRho#5]
Hi,

I have a theoretical question about the way invariant sites are considered in your model.

I do not master the mathematical aspect of your model and I spent time to think about the presence/absence of invariant sites in the vcf file without finding a clear solution. Is it mandatory to include invariant sites in the vcf file as in Booker et al. 2021? How presence/absence of invariant sites would affect the estimates?

Thank you,

Thomas Brazier

**Comment by samebdon** [comment]
Hi Thomas,

The expectation is based on the distribution of variants, and only the positions of variant sites are processed. So you shouldn't need to include invariant sites, as invariant positions are implied. Does that help?

Cheers,
Sam

**Comment by ThomasBrazier** [comment]
Thanks.

It was the intuition I had, but I wasn't sure. It is a good news for me, as my data contains only variant sites.
